### ISSUE TITLE
Propolis panic potentially related to some crucible operations

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/crucible#1571]
I have a group of VMs provisioned with identical config using Terraform. Some VM stay running while the others all went into `failed` state after running for a while and then hitting propolis panic. Here is what I saw in one of the core files:
```
BRM42220014 # mdb /pool/ext/8be8c577-23ac-452e-a205-6d9c95088f61/crypt/debug/core.oxz_propolis-server_828f7793-0916-43db-924a-da37dc1be196.propolis-server.28428.1732575554
Loading modules: [ libumem.so.1 libnvpair.so.1 libc.so.1 ld.so.1 ]
> ::status
debugging core file of propolis-server (64-bit) from oxz_propolis-server_828f7793-0916-43db-924a-da37dc1be196
initial argv: /opt/oxide/propolis-server/bin/propolis-server run /var/svc/manifest/site/propo
threading model: native threads
status: process terminated by SIGABRT (Abort), pid=28428 uid=0 code=-1
> $C ! demangle
fffff5ffeb5fe770 libc.so.1`_lwp_kill+0xa()
fffff5ffeb5fe7a0 libc.so.1`raise+0x22(6)
fffff5ffeb5fe7f0 libc.so.1`abort+0x58()
fffff5ffeb5fe800 0x28b5f19()
fffff5ffeb5fe810 0x28b5f09()
fffff5ffeb5fe870 rust_panic+0xd()
fffff5ffeb5fe950 std::panicking::rust_panic_with_hook::hfbc2313a4516d465+0x8bf()
fffff5ffeb5fe990 std::panicking::begin_panic_handler::{{closure}}::h8b784919ae9f75f5+0x95()
fffff5ffeb5fe9a0 0x289c0c9()
fffff5ffeb5fe9f0 0x289ea54()
fffff5ffeb5fea40 0x28e3452()
fffff5ffeb5feaa0 0x18587ae()
fffff5ffeb5feba0 crucible::downstairs::Downstairs::enqueue::_$u7b$$u7b$closure$u7d$$u7d$::hf6ede5fa3a4ef3cb (.llvm.13013778811916355444)+0x55()
fffff5ffeb5ff010 crucible::downstairs::Downstairs::enqueue::hfc0405a64f20e3d4 (.llvm.12065988445570034316)+0x22d()
fffff5ffeb5ff190 crucible::downstairs::Downstairs::submit_flush::h46a2044513dd81a7+0x38f()
fffff5ffeb5ff6a0 crucible::upstairs::Upstairs::apply::ha06dc31168255263+0x1429()
fffff5ffeb5ffaa0 crucible::up_main::_$u7b$$u7b$closure$u7d$$u7d$::h8181247de9becd81 (.llvm.17401144747463235486)+0x900()
fffff5ffeb5ffb00 tokio::runtime::task::core::Core<T,S>::poll::h244bb85a3090c3c1+0x39()
fffff5ffeb5ffb60 tokio::runtime::task::harness::Harness<T,S>::poll::h9f02de55c52feaae+0x5b()
fffff5ffeb5ffbb0 tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hf1f58caa77b3deaa+0x143()
fffff5ffeb5ffc60 tokio::runtime::context::scoped::Scoped<T>::set::h39fc6aaf11255da0+0x64e()
fffff5ffeb5ffd10 tokio::runtime::context::runtime::enter_runtime::hc0f9531eef3a7e31+0x19a()
fffff5ffeb5ffd50 tokio::runtime::scheduler::multi_thread::worker::run::h23759ed2aeecde6e+0x7c()
fffff5ffeb5ffdc0 tokio::runtime::task::core::Core<T,S>::poll::h2cda0671805666db+0x72()
fffff5ffeb5ffe50 tokio::runtime::task::harness::Harness<T,S>::poll::h2e5427bf6a764cb2+0x8a()
fffff5ffeb5ffef0 tokio::runtime::blocking::pool::Inner::run::h6492870387739b28+0xe4()
fffff5ffeb5fff30 std::sys::backtrace::__rust_begin_short_backtrace::h51c197049117dadd+0x3e()
fffff5ffeb5fff80 core::ops::function::FnOnce::call_once{{vtable.shim}}::h13ba99e369d3c88e+0x7e()
fffff5ffeb5fffb0 std::sys::pal::unix::thread::Thread::new::thread_start::hce81063711d644a3+0x1b()
fffff5ffeb5fffe0 libc.so.1`_thrp_setup+0x77(fffff5ffeef55240)
fffff5ffeb5ffff0 libc.so.1`_lwp_start()
```
The core file and logs are being copied to `/staff/core/crucible-1571`.

**Comment by askfongjojo** [comment]
Another observation: 5 out of the 5 VMs created concurrently failed (these 5 also have a smaller disk), whereas 2 out of 5 failed when creating sequentially.

**Comment by askfongjojo** [comment]
The last bit of the propolis log:
```
22:59:13.050Z INFO propolis-server (vm_state_driver): checking for deactivation
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): not ready to deactivate due to state Deactivated
     = downstairs
    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): downstairs task for 0 stopped due to RequestedStop(Deactivated)
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ds_transition from Deactivated to New
     = downstairs
    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): [0] Transition from Deactivated to New
     = downstairs
    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): checking for deactivation
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ready to deactivate from state New
     = downstairs
    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ready to deactivate from state New
     = downstairs
    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ready to deactivate from state New
     = downstairs
    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): All DS in the proper state! -> INIT
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): client task is exiting
     = downstairs
    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): Scrub of volume 9a69edc0-17d5-40e3-98bf-966af39f4b5b completed, remove parent
22:59:13.050Z INFO propolis-server (vm_state_driver): client task is exiting
     = downstairs
    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): client task is exiting
     = downstairs
    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
thread 'tokio-rt-vmm' panicked at /home/build/.cargo/git/checkouts/crucible-f3b5bdecdc6486d6/1d82cc9/upstairs/src/client.rs:977:36:
enqueue should not be called from state New
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ Nov 25 22:59:15 Stopping because all processes in service exited. ]
[ Nov 25 22:59:15 Executing stop method (:kill). ]
```

**Comment by leftwo** [comment]
So here is what I think has happened.

Looking in `system-illumos-propolis-server:default.log` from `/staff/core/crucible-1571` which I think is the proplis log for
oxz_propolis-server_828f7793-0916-43db-924a-da37dc1be196.propolis-server.28428.1732575554

The connection in question is for the read only parent, and we have finished scrubbing it, told nexus and now it's time to deactivate our connection to it.

```
22:59:13.009Z INFO propolis-server (vm_state_driver): Scrub at offset 4194304/4194304 sp:4194304
22:59:13.042Z INFO propolis-server (vm_state_driver): Scrub 9a69edc0-17d5-40e3-98bf-966af39f4b5b done in 442 seconds. Retries:0 scrub_size:131072 size:4194304 pause_milli:25
22:59:13.049Z INFO propolis-server (vm_state_driver): Deactivate read only parent 9a69edc0-17d5-40e3-98bf-966af39f4b5b
22:59:13.049Z INFO propolis-server (vm_state_driver): Request to deactivate this guest
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.049Z INFO propolis-server (vm_state_driver): checking for deactivation
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.049Z INFO propolis-server (vm_state_driver): [0] deactivate, no work so YES
```

We want to deactivate because once we tell nexus, nexus can destroy the ROP, then crucible agent can re-use the port number for some other region.  We had an issue in the past where an upstairs was still trying to connect to some long ago scrubbed ROP (even though it was not going to talk to it).  Eventually the IP:Port was reused and when the old upstairs noticed and connected, it paniced because the region info did not match.

But, I digress, the propolis log continues and disconnects from all the ROP downstairs:
```
22:59:13.049Z INFO propolis-server (vm_state_driver): ds_transition from Active to Deactivated
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.049Z INFO propolis-server (vm_state_driver): [0] Transition from Active to Deactivated
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.049Z INFO propolis-server (vm_state_driver): deactivated client 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.049Z INFO propolis-server (vm_state_driver): [1] deactivate, no work so YES
     = downstairs
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e 
22:59:13.049Z INFO propolis-server (vm_state_driver): ds_transition from Active to Deactivated
     = downstairs    client = 1 
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e 
22:59:13.049Z INFO propolis-server (vm_state_driver): [1] Transition from Active to Deactivated
     = downstairs    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): deactivated client 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e 
22:59:13.050Z INFO propolis-server (vm_state_driver): [2] deactivate, no work so YES
     = downstairs
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ds_transition from Active to Deactivated
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): [2] Transition from Active to Deactivated
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): deactivated client 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): not ready to deactivate due to state Deactivated
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): client task is sending Done(RequestedStop(Deactivated))
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): client task is sending Done(RequestedStop(Deactivated))
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): downstairs task for 2 stopped due to RequestedStop(Deactivated)
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e

```
The downstairs have now all transitioned to `Deactivated`, but things continue
```
22:59:13.050Z INFO propolis-server (vm_state_driver): ds_transition from Deactivated to New
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): [2] Transition from Deactivated to New
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): downstairs disconnected
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): client task is sending Done(RequestedStop(Deactivated))
     = downstairs    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): downstairs disconnected
     = downstairs    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): downstairs disconnected
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): checking for deactivation
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): not ready to deactivate due to state Deactivated
     = downstair    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): downstairs task for 1 stopped due to RequestedStop(Deactivated)
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ds_transition from Deactivated to New
     = downstairs client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): [1] Transition from Deactivated to New
     = downstairs    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): checking for deactivation
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): not ready to deactivate due to state Deactivated
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z WARN propolis-server (vm_state_driver): downstairs task for 0 stopped due to RequestedStop(Deactivated)
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ds_transition from Deactivated to New
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): [0] Transition from Deactivated to New
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): checking for deactivation
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ready to deactivate from state New
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ready to deactivate from state New
     = downstairs    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): ready to deactivate from state New
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
```
Now, all the downstairs have transitioned back to New
```
22:59:13.050Z INFO propolis-server (vm_state_driver): All DS in the proper state! -> INIT
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): client task is exiting
     = downstairs    client = 2
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): Scrub of volume 9a69edc0-17d5-40e3-98bf-966af39f4b5b completed, remove parent
22:59:13.050Z INFO propolis-server (vm_state_driver): client task is exiting
     = downstairs    client = 1
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
22:59:13.050Z INFO propolis-server (vm_state_driver): client task is exiting
     = downstairs    client = 0
    session_id = 0bd32473-62fc-4eb0-a31c-a14508404b7e
thread 'tokio-rt-vmm' panicked at /home/build/.cargo/git/checkouts/crucible-f3b5bdecdc6486d6/1d82cc9/upstairs/sr/client.rs:977:36:
enqueue should not be called from state New
```

And, we hit our panic.  So I believe we are trying to submit an IO to a deactivated\New set of downstairs.

It might be nice if the panic string also included the session_id, as I suspect it's from the ROP session, but it would be better if the session ID was included to remove any ambiguity.

**Comment by leftwo** [comment]
Potential fix: https://github.com/oxidecomputer/crucible/pull/1573
