### ISSUE TITLE
Crucible downstairs went away and then the upstairs panic'd 

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#741]
On dogfood, an instance stopped responding on the console.
Under further investigation, we see that the propolis instance has paniced in crucible land:

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/build/.cargo/git/checkouts/crucible-f3b5bdecdc6486d6/9f69dea/upstairs/src/lib.rs:2587:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is from the `in_progress()` method:
```
    fn in_progress(&mut self, ds_id: u64, client_id: u8) -> Option<IOop> {
        let job = self.ds_active.get_mut(&ds_id).unwrap();
````

So, the upstairs was trying to move a job to `InProgress`, but that (unknown) job ID
was not on the `ds_active` list.

**Comment by leftwo** [comment]
This issue was on sled 21, BRM42220026
Propolis server log is here: /net/catacomb/data/staff/core/crucible-741//propolis-server.log

**Comment by leftwo** [comment]
The disk in question was this one:
```
alan@atrium:omicron-new-files$  oxide disk view --disk test-drive-1 --project try
success
Disk {
    block_size: ByteCount(
        512,
    ),
    description: "ubuntu 22.04 mysql instance 1",
    device_path: "/mnt/test-drive-1",
    id: 2ee4b9bf-1829-4935-b389-2573012251a3,
    image_id: Some(
        7146256c-76d9-4f3d-a2e1-b4219d3fbc38,
    ),
    name: Name(
        "test-drive-1",
    ),
    project_id: 549f44d7-b0cd-4532-b94d-9cae7baab5d3,
    size: ByteCount(
        53687091200,
    ),
    snapshot_id: None,
    state: Attached(
        642c108e-5cbe-4569-bf43-b682905a090c,
    ),
    time_created: 2023-05-23T21:07:56.030196Z,
    time_modified: 2023-05-23T21:07:56.030196Z,
}
```

**Comment by leftwo** [comment]
I actually got the disk ID from the VolumeConstructionRequestj in the propolis logs.
Here is that VCR:
```
21:08:22.385Z INFO propolis-server: Creating Crucible disk from request Volume 
{ 
    id: 2ee4b9bf-1829-4935-b389-2573012251a3, 
    block_size: 512, 
    sub_volumes: [
        Region { 
            block_size: 512,
            blocks_per_extent: 131072, 
            extent_count: 800, 
            opts: CrucibleOpts { id: 2ee4b9bf-1829-4935-b389-2573012251a3, 
                target: [[fd00:1122:3344:105::c]:19000, [fd00:1122:3344:10b::6]:19000, [fd00:1122:3344:10b::7]:19000], 
                lossy: false, 
                flush_timeout: None, 
                key: Some("YDBwG4VsyrgFzXlzlw+OmzzWFhAu1Wy5jdDl13s9bus="), 
                cert_pem: None, 
                key_pem: None, 
                root_cert_pem: None, 
                control: None, 
                read_only: false 
            },  
            gen: 1 }
    ],
    read_only_parent: Some(
        Volume { 
            id: a1f36058-e45a-43c0-b3a3-ae581979b787, 
            block_size: 512, 
            sub_volumes: [
                Region { 
                    block_size: 512,
                    blocks_per_extent: 131072,
                    extent_count: 32,
                    opts: CrucibleOpts { 
                        id: dea28ea2-848c-4bf6-8b8b-f550541464f7,
                        target: [[fd00:1122:3344:105::8]:19001, [fd00:1122:3344:10a::a]:19001, [fd00:1122:3344:107::c]:19001],
                        lossy: false,
                        flush_timeout: None,
                        key: Some("SrtUZxNjHdp7XRGStNsq8UZmctmq6ZGChGZwRhIaoQQ="),
                        cert_pem: None,
                        key_pem: None,
                        root_cert_pem: None,
                        control: None,
                        read_only: true 
                    },  
                    gen: 2
                }   
            ],
            read_only_parent: None 
        }
    )
}
```

From the logs, we can also get the target info for the downstairs as well.
Here is the UUID for the volume, then the connections for each downstairs client.
```
May 23 21:08:22.386 INFO Crucible stats registered with UUID: 2ee4b9bf-1829-4935-b389-2573012251a3
May 23 21:08:22.386 INFO Crucible 2ee4b9bf-1829-4935-b389-2573012251a3 has session id: ad0c584c-7c91-4fa4-9691-fda80a8a2dad
May 23 21:08:22.386 INFO [0] connecting to [fd00:1122:3344:105::c]:19000, looper: 0
May 23 21:08:22.386 INFO [1] connecting to [fd00:1122:3344:10b::6]:19000, looper: 1
May 23 21:08:22.386 INFO [2] connecting to [fd00:1122:3344:10b::7]:19000, looper: 2
```

And, further down, we see the upstairs go online:
```
May 23 21:08:22.430 INFO 2ee4b9bf-1829-4935-b389-2573012251a3 is now active with session: c8ef300d-3d75-4d35-919f-61d77f7b44bd
```

And, shortly there after, trouble begins:
Downstairs 2 then 1 both go offline, but quickly come back:
```
May 23 21:09:13.493 WARN [2] downstairs disconnected
May 23 21:09:13.493 INFO [2] 2ee4b9bf-1829-4935-b389-2573012251a3 Gone missing, transition from Active to Offline
May 23 21:09:13.493 INFO [2] 2ee4b9bf-1829-4935-b389-2573012251a3 connection to [fd00:1122:3344:10b::7]:19000 closed, looper: 2
May 23 21:09:13.493 INFO [2] [fd00:1122:3344:10b::7]:19000 task reports connection:false
May 23 21:09:13.493 INFO 2ee4b9bf-1829-4935-b389-2573012251a3 Active Active Offline
May 23 21:09:13.493 INFO [2] [fd00:1122:3344:10b::7]:19000 task reports offline
May 23 21:09:13.494 ERRO [fd00:1122:3344:10b::6]:19000: proc: Connection reset by peer (os error 131), looper: 1
May 23 21:09:13.494 INFO [1] 2ee4b9bf-1829-4935-b389-2573012251a3 Gone missing, transition from Active to Offline
May 23 21:09:13.494 INFO [1] 2ee4b9bf-1829-4935-b389-2573012251a3 connection to [fd00:1122:3344:10b::6]:19000 closed, looper: 1
May 23 21:09:13.494 INFO [1] [fd00:1122:3344:10b::6]:19000 task reports connection:false
May 23 21:09:13.494 INFO 2ee4b9bf-1829-4935-b389-2573012251a3 Active Offline Offline
May 23 21:09:13.494 INFO [1] [fd00:1122:3344:10b::6]:19000 task reports offline
May 23 21:09:14.495 INFO [1] 2ee4b9bf-1829-4935-b389-2573012251a3 looper connected, looper: 1
May 23 21:09:14.495 INFO [1] Proc runs for [fd00:1122:3344:10b::6]:19000 in state Offline
May 23 21:09:14.495 INFO [1] client re-new 97 jobs since flush 1022, : downstairs
May 23 21:09:14.495 INFO [2] 2ee4b9bf-1829-4935-b389-2573012251a3 looper connected, looper: 2
May 23 21:09:14.495 INFO [2] Proc runs for [fd00:1122:3344:10b::7]:19000 in state Offline
May 23 21:09:14.495 INFO [2] client re-new 97 jobs since flush 1022, : downstairs
May 23 21:09:14.496 INFO [1] upstairs guest_io_ready=TRUE, promote! session c8ef300d-3d75-4d35-919f-61d77f7b44bd
May 23 21:09:14.496 INFO [2] upstairs guest_io_ready=TRUE, promote! session c8ef300d-3d75-4d35-919f-61d77f7b44bd
May 23 21:09:14.496 INFO [1] downstairs client at [fd00:1122:3344:10b::6]:19000 has UUID 92155e3f-318c-4327-830c-8da7140304e0
May 23 21:09:14.496 INFO [1] Got region def RegionDefinition { block_size: 512, extent_size: Block { value: 131072, shift: 9 }, extent_count: 800, uuid: 92155e3f-318c-4327-830c-8da7140304e0, encrypted: true }
May 23 21:09:14.496 INFO Returning client:1 UUID:92155e3f-318c-4327-830c-8da7140304e0 matches
May 23 21:09:14.496 INFO [1] send last flush ID to this DS: 1022
May 23 21:09:14.496 INFO 2ee4b9bf-1829-4935-b389-2573012251a3 Active Offline Offline
May 23 21:09:14.496 INFO [2] downstairs client at [fd00:1122:3344:10b::7]:19000 has UUID 56d2be8d-23d5-4b39-8b43-19ed5c8a2d85
May 23 21:09:14.496 INFO [2] Got region def RegionDefinition { block_size: 512, extent_size: Block { value: 131072, shift: 9 }, extent_count: 800, uuid: 56d2be8d-23d5-4b39-8b43-19ed5c8a2d85, encrypted: true }
May 23 21:09:14.496 INFO Returning client:2 UUID:56d2be8d-23d5-4b39-8b43-19ed5c8a2d85 matches
May 23 21:09:14.496 INFO [2] send last flush ID to this DS: 1022
May 23 21:09:14.496 INFO 2ee4b9bf-1829-4935-b389-2573012251a3 Active Offline Offline
May 23 21:09:14.496 INFO [1] replied this last flush ID: 1022
May 23 21:09:14.496 INFO [1] 2ee4b9bf-1829-4935-b389-2573012251a3 (c8ef300d-3d75-4d35-919f-61d77f7b44bd) Active Offline Offline ds_transition to Replay
May 23 21:09:14.496 INFO [1] Transition from Offline to Replay
May 23 21:09:14.496 INFO [1] 2ee4b9bf-1829-4935-b389-2573012251a3 Transition from Replay to Active
May 23 21:09:14.496 INFO [1] 2ee4b9bf-1829-4935-b389-2573012251a3 (c8ef300d-3d75-4d35-919f-61d77f7b44bd) Active Replay Offline ds_transition to Active
May 23 21:09:14.496 INFO [1] Transition from Replay to Active
May 23 21:09:14.496 INFO [1] Starts cmd_loop
May 23 21:09:14.496 INFO [1] [fd00:1122:3344:10b::6]:19000 task reports connection:true
May 23 21:09:14.496 INFO 2ee4b9bf-1829-4935-b389-2573012251a3 Active Active Offline
May 23 21:09:14.496 INFO [2] replied this last flush ID: 1022
May 23 21:09:14.496 INFO [2] 2ee4b9bf-1829-4935-b389-2573012251a3 (c8ef300d-3d75-4d35-919f-61d77f7b44bd) Active Active Offline ds_transition to Replay
May 23 21:09:14.496 INFO [2] Transition from Offline to Replay
May 23 21:09:14.496 INFO [2] 2ee4b9bf-1829-4935-b389-2573012251a3 Transition from Replay to Active
May 23 21:09:14.496 INFO [2] 2ee4b9bf-1829-4935-b389-2573012251a3 (c8ef300d-3d75-4d35-919f-61d77f7b44bd) Active Active Replay ds_transition to Active
May 23 21:09:14.496 INFO [2] Transition from Replay to Active
May 23 21:09:14.496 INFO [2] Starts cmd_loop
May 23 21:09:14.496 INFO [2] [fd00:1122:3344:10b::7]:19000 task reports connection:true
May 23 21:09:14.496 INFO 2ee4b9bf-1829-4935-b389-2573012251a3 Active Active Active
```

**Comment by leftwo** [comment]
Trouble soon resumes, as we see from the logs as flow control kicks in with downstairs 1 and 2 again:
```
21:48:33.982Z INFO propolis-server: piix3pm ignored cfg read
    dev = chipset
    offset = 0j    register = DevResJ
May 23 21:48:37.953 WARN [2] flow control start 
May 23 21:48:38.954 WARN [2] flow control end 
May 23 21:48:40.695 WARN [1] flow control start 
May 23 21:48:40.772 WARN [2] flow control start 
May 23 21:48:41.696 WARN [1] flow control end 
May 23 21:48:41.773 WARN [2] flow control end 
May 23 21:48:45.187 WARN [2] flow control start 
May 23 21:48:45.594 WARN [1] flow control start 
May 23 21:48:46.189 WARN [2] flow control end 
May 23 21:48:46.595 WARN [1] flow control end 
21:55:50.514Z INFO propolis-server (serial task): Removing closed serial connection 7.
    local_addr = [fd00:1122:3344:101::23]:12400
    method = PUT
    remote_addr = [fd00:1122:3344:101::1]:44076
    req_id = 983f9bb3-0dd9-41e0-855d-4aa4140f89da
    uri = /instance
```
Then, downstairs 2 finally appears to stop responding or get full (the task sending it work has
filled up, meaing it's not making any progress):

```
22:05:57.109Z INFO propolis-server: request completed
    local_addr = [fd00:1122:3344:101::23]:12400
    method = GET
    remote_addr = [fd00:1122:3344:106::4]:64515
    req_id = 8fdeec8b-2b8a-44c4-9b6e-f00b8e21d3b1
    response_code = 101
    uri = /instance/serial?most_recent=262144
May 23 22:07:22.451 WARN [1] flow control start 
May 23 22:07:23.468 WARN [1] flow control end 
May 23 22:07:37.285 WARN Full(17172) Failed to notify client 2 of work 17172
May 23 22:07:37.294 WARN Full(17173) Failed to notify client 2 of work 17173
May 23 22:07:37.303 WARN Full(17174) Failed to notify client 2 of work 17174
May 23 22:07:37.361 WARN Full(17175) Failed to notify client 2 of work 17175
May 23 22:07:37.374 WARN Full(17176) Failed to notify client 2 of work 17176
May 23 22:07:37.383 WARN Full(17177) Failed to notify client 2 of work 17177
```

The upstairs has soon had enough, so it kicks out downstairs 1:
(New issue, that "too many outstanding jobs" log message args are swizzled)
```
May 23 22:09:11.967 WARN Full(21804) Failed to notify client 1 of work 21804
May 23 22:09:11.968 WARN Full(21805) Failed to notify client 1 of work 21805
May 23 22:09:11.969 WARN Full(21806) Failed to notify client 1 of work 21806
May 23 22:09:11.969 WARN [up] downstairs 1001 failed, too many outstanding jobs 1
May 23 22:09:11.969 INFO [1] client skip 1250 in process jobs because fault, : downstairs
May 23 22:09:11.969 INFO 1 change 21943 to fault skipped, : downstairs
May 23 22:09:11.969 INFO 1 change 21944 to fault skipped, : downstairs
May 23 22:09:11.969 INFO 1 change 21945 to fault skipped, : downstairs
```
...
```
May 23 22:09:12.203 INFO [1] 2ee4b9bf-1829-4935-b389-2573012251a3 (c8ef300d-3d75-4d35-919f-61d77f7b44bd) Active Active Active ds_transition to Faulted
```

Then, we hit the panic.
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/build/.cargo/git/checkouts/crucible-f3b5bdecdc6486d6/9f69dea/upstairs/src/lib.rs:2587:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Before we get to the panic, let's see if there is anything in the log for downstairs 2.  From the 
earlier log messages we can gather enough info to find it.
```
May 23 21:08:22.391 INFO [2] downstairs client at [fd00:1122:3344:10b::7]:19000 has UUID 56d2be8d-23d5-4b39-8b43-19ed5c8a2d85
```
That gives us both an I.P. address, and a UUID.

**Comment by leftwo** [comment]
Using `pilot host exec` from the switch zone, we can find the dataset for our downstairs 2:
```
BRM42220051-switch # pilot host exec -c "zfs list | grep 56d2be8d-23d5-4b39-8b43
-19ed5c8a2d85||true" 10 11 12 13 16 17 19 21 23 24 28
10  BRM42220009        ok: 
11  BRM42220057        ok: 
12  BRM42220018        ok: 
13  BRM44220005        ok: 
16  BRM42220086        ok: oxp_17370cb0-8a58-493b-86e0-d64209a28d7d/crucible/regions/56d2be8d-23d5-4b39-8b43-19ed5c8a2d85  8.02G  2.81T     8.02G  /data/regions/56d2be8d-23d5-4b39-8b43-19ed5c8a2d85
17  BRM42220006        ok: 
19  BRM42220017        ok: 
21  BRM42220026        ok: 
23  BRM42220031        ok: 
24  BRM42220014        ok: 
28  BRM44220010        ok: 
```

So, it's sled 16 that has the dataset, which means it will have our downstairs zone as well.
We can actually see the zone name right there in the output:
`oxp_17370cb0-8a58-493b-86e0-d64209a28d7d`

And, sure enough, there inside that zone is a downstairs service matching our UUID:
```
root@oxz_crucible_oxp_17370cb0-8a58-493b-86e0-d64209a28d7d:~# svcs | grep 56d2be8d
online         14:07:57 svc:/oxide/crucible/downstairs:downstairs-56d2be8d-23d5-4b39-8b43-19ed5c8a2d85
```

The log file for that zone is here: /net/catacomb/data/staff/core/crucible-741/downstairs-56d2be8d-23d5-4b39-8b43-19ed5c8a2d85.log

From that log, we can see the downstairs comes up, version info checks out:
```
May 23 21:07:57.936 INFO Opened existing region file "/data/regions/56d2be8d-23d5-4b39-8b43-19ed5c8a2d85/region.json"
May 23 21:07:58.676 INFO UUID: 56d2be8d-23d5-4b39-8b43-19ed5c8a2d85
May 23 21:07:58.676 INFO Blocks per extent:131072 Total Extents: 800
May 23 21:07:58.676 INFO Crucible Version: Crucible Version: 0.0.1
Commit SHA: 9f69deab230079a5bae4a10a099d7fc1f3d29df7
Commit timestamp: 2023-05-10T15:02:44.000000000Z  branch: main
rustc: 1.66.1 stable x86_64-unknown-illumos
Cargo: x86_64-unknown-illumos  Debug: false Opt level: 3, task: main
May 23 21:07:58.676 INFO Upstairs <-> Downstairs Message Version: 2, task: main
May 23 21:07:58.677 INFO Using address: [fd00:1122:3344:10b::7]:19000, task: main
May 23 21:07:58.677 INFO Repair listens on [fd00:1122:3344:10b::7]:23000, task: repair
May 23 21:07:58.677 INFO listening, local_addr: [fd00:1122:3344:10b::7]:23000, task: repair
May 23 21:07:58.677 INFO Using repair address: [fd00:1122:3344:10b::7]:23000, task: main
May 23 21:07:58.677 INFO No SSL acceptor configured, task: main
May 23 21:07:58.677 INFO listening on [fd00:1122:3344:10b::7]:19000, task: main
```

We see our upstairs connection happen and the activation:
```
May 23 21:08:22.387 INFO accepted connection from [fd00:1122:3344:101::23]:48098, task: main
May 23 21:08:22.387 INFO Connection request from 2ee4b9bf-1829-4935-b389-2573012251a3 with version 2, task: proc
May 23 21:08:22.387 INFO upstairs UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } connected, version 2, task: proc
May 23 21:08:22.391 INFO UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } is now active (read-write)
```
Negotiation and reconciliation checks happen, all good
```
Current flush_numbers [0..12]: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
May 23 21:08:22.429 INFO Downstairs has completed Negotiation, task: proc
```
Then... (and maybe some amount of work happens first) we hit a timeout. The downstairs does not hear anything (not even a ping) from the upstairs for 50 seconds, and so it closes the connection:
```
May 23 21:09:13.493 ERRO connection ([fd00:1122:3344:101::23]:48098) Exits with error: inactivity timeout
```
We get a reconnect from our upstairs
```
May 23 21:09:14.495 INFO accepted connection from [fd00:1122:3344:101::23]:37784, task: main
May 23 21:09:14.496 INFO Connection request from 2ee4b9bf-1829-4935-b389-2573012251a3 with version 2, task: proc
May 23 21:09:14.496 INFO upstairs UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } connected, version 2, task: proc
May 23 21:09:14.496 WARN Attempting RW takeover from UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } to UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 }
May 23 21:09:14.496 WARN Signaling to UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } thread that UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } is being promoted (read-write)
May 23 21:09:14.496 ERRO Error while signaling to UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } thread: SendError(UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 })
May 23 21:09:14.496 INFO UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } is now active (read-write)
May 23 21:09:14.496 INFO Set last flush 1022, task: proc
May 23 21:09:14.497 INFO Downstairs has completed Negotiation, task: proc
```
But then, a little more than a minute later, our upstairs disconnects from us
```
May 23 22:09:17.549 WARN upstairs UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } disconnected, 0 jobs left, task: main
May 23 22:09:17.550 WARN upstairs UpstairsConnection { upstairs_id: 2ee4b9bf-1829-4935-b389-2573012251a3, session_id: c8ef300d-3d75-4d35-919f-61d77f7b44bd, gen: 1 } was previously active, clearing, task: main
May 23 22:09:17.550 INFO connection ([fd00:1122:3344:101::23]:37784): all done
```
At this point, the connection is gone, no more upstairs.


So, no smoking gun yet, some ideas.
1. The upstairs could have worked itself into a deadlock and really is not sending traffic to the downstairs (though other tasks are making progress in other areas).
2. There is some network connection problem between the upstairs and this downstairs that is resulting in traffic not getting between the two.
3. Something else that I've not thought of yet.

**Comment by leftwo** [comment]
It was discovered (thanks @rcgoodfellow ) that sled16 (downstairs) and sled 21 (propolis) had different MTU set, and this would have caused network problems.  So, this could explain why the downstairs
was coming and going and not making progress.

**Comment by askfongjojo** [comment]
Thank you all for tracking down the root cause! I am glad that it's not a bug (but it exposed some error handling gaps elsewhere). I've run the same fio test many times previously so I don't believe the disk i/o could have caused the downstair disconnect issue. I'm happy to have this issue mark closed.

**Comment by leftwo** [comment]
I want to add a note about the panic before closing, as that is reported here as well.
I'm pretty sure I know how it came about, but I'll write that part up then close the issue.

**Comment by askfongjojo** [comment]
Hmm so another issue happened also on a Debian 11 instance while running fio. The errors are different this time:
```
[  740.126727] nvme nvme0: I/O 295 QID 4 timeout, aborting
[  740.127451] nvme nvme0: Abort status: 0x6
[  740.127962] nvme nvme0: I/O 303 QID 4 timeout, aborting
[  740.128649] nvme nvme0: Abort status: 0x6
[  740.134747] nvme nvme0: I/O 302 QID 4 timeout, aborting
[  740.135729] nvme nvme0: Abort status: 0x6
[  740.136251] nvme nvme0: I/O 308 QID 4 timeout, aborting
[  740.136955] nvme nvme0: Abort status: 0x6
[  740.142756] nvme nvme0: I/O 311 QID 4 timeout, aborting
[  740.143695] nvme nvme0: Abort status: 0x6
[  740.144189] nvme nvme0: I/O 314 QID 4 timeout, aborting
[  740.144867] nvme nvme0: Abort status: 0x6
[  740.145369] nvme nvme0: I/O 317 QID 4 timeout, aborting
[  740.146093] nvme nvme0: Abort status: 0x6
[  740.150753] nvme nvme0: I/O 256 QID 4 timeout, aborting
[  740.151699] nvme nvme0: Abort status: 0x6
[  740.152230] nvme nvme0: I/O 261 QID 4 timeout, aborting
[  740.152920] nvme nvme0: Abort status: 0x6
[  740.158866] nvme nvme0: I/O 262 QID 4 timeout, aborting
[  740.159797] nvme nvme0: Abort status: 0x6
[  740.160287] nvme nvme0: I/O 267 QID 4 timeout, aborting
[  740.160967] nvme nvme0: Abort status: 0x6
[  740.166724] nvme nvme0: I/O 269 QID 4 timeout, aborting
[  740.167408] nvme nvme0: Abort status: 0x6
[  740.167894] nvme nvme0: I/O 276 QID 4 timeout, aborting
[  740.168564] nvme nvme0: Abort status: 0x6
[  834.833438] nvme nvme0: I/O 257 QID 4 timeout, aborting
[  834.834473] nvme nvme0: Abort status: 0x6
[  834.834956] nvme nvme0: I/O 265 QID 4 timeout, aborting
[  834.835640] nvme nvme0: Abort status: 0x6
[  834.836133] nvme nvme0: I/O 272 QID 4 timeout, aborting
[  834.836825] nvme nvme0: Abort status: 0x6
[  834.837580] nvme nvme0: I/O 275 QID 4 timeout, aborting
[  834.838505] nvme nvme0: Abort status: 0x6
[  834.839190] nvme nvme0: I/O 278 QID 4 timeout, aborting
[  834.840078] nvme nvme0: Abort status: 0x6
[  834.840753] nvme nvme0: I/O 281 QID 4 timeout, aborting
[  834.841700] nvme nvme0: Abort status: 0x6
[  834.842376] nvme nvme0: I/O 284 QID 4 timeout, aborting
[  834.843280] nvme nvme0: Abort status: 0x6
[  834.843950] nvme nvme0: I/O 305 QID 4 timeout, aborting
[  834.844838] nvme nvme0: Abort status: 0x6
[  834.845570] nvme nvme0: I/O 308 QID 4 timeout, aborting
[  834.846525] nvme nvme0: Abort status: 0x6
[  835.409430] nvme nvme0: I/O 256 QID 4 timeout, aborting
[  835.410731] nvme nvme0: Abort status: 0x6
[  856.336244] nvme nvme0: I/O 285 QID 4 timeout, aborting
[  856.337198] nvme nvme0: Abort status: 0x6
[  865.039813] nvme nvme0: I/O 266 QID 4 timeout, aborting
[  865.041001] nvme nvme0: Abort status: 0x6
[  865.041698] nvme nvme0: I/O 272 QID 4 timeout, reset controller
[  865.109199] nvme nvme0: 4/0/0 default/read/poll queues
...(many more of these same errors until I kill -9 fio)
```
It was writing a 10G file when that happened:
```
fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test07-bs32k-10G-io128-randrw80 --filename=size-10G --bs=32k --size=10G --iodepth=128 --readwrite=randrw --rwmixread=80 > test07-bs32k-10G-io128-randrw80
```
The instance id is `e114b348-9c73-4f62-92e4-eaf67b2acb9d` and it's no longer accessible (I haven't tried rebooting it yet).
```
root@[fd00:1122:3344:106::6]:32221/omicron> select name, active_propolis_id, active_sled_id from instance where id = 'e114b348-9c73-4f62-92e
4-eaf67b2acb9d';
         name        |          active_propolis_id          |            active_sled_id
---------------------+--------------------------------------+---------------------------------------
  run-some-fio-again | 05975657-b8f1-4884-8f15-25c053f6fcbd | aa7c82d9-6e59-406e-b1e3-3648890b4bec
(1 row)
```

**Comment by leftwo** [comment]
For what it's worth, my two instances that have downstairs on cubby 16 still have a problem even after the MTU change.  I wonder if, because they started before the MTU was updated, if they are not going to get better.

**Comment by rcgoodfellow** [comment]
@leftwo if you want to show me what interfaces are being used for this, i can check the L3 MTUs in addition the the L2 MTUs that were fixed previously.

**Comment by leftwo** [comment]
> @leftwo if you want to show me what interfaces are being used for this, i can check the L3 MTUs in addition the the L2 MTUs that were fixed previously.

I no longer believe my issue is due to networking, but due to my propolis-server having paniced, then not being able to recover from that situation.  My instance is stuck in purgatory now.

**Comment by askfongjojo** [comment]
Ok, so the error I saw was unrelated to crucible - the zone hit some error and panicked the sled-agent there (sled in gc11). By the time I ran fio, the zone was on the way being destroyed by the sled-agent. I'll investigate further and file a ticket as needed.

**Comment by leftwo** [comment]
With the refactor of the upstairs (one true task), the way this panic happened is no longer possible.
