### ISSUE TITLE
Crucible should allow downstairs replacement before it is active.

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#871]
New title for this issue,
Currently the Upstairs panics when trying to replace a downstairs before it is active:

To reproduce.

start three downstairs with dsc,

start cli server:
```
alan@atrium:crucible$ ./target/release/crutest cli-server -t 127.0.0.1:8810 -t 127.0.0.1:8820 -t 127.0.0.1:8830
Aug 17 01:23:41.182 INFO Upstairs starts
Aug 17 01:23:41.183 INFO Crucible Version: BuildInfo {
    version: "0.0.1",
    git_sha: "175a8cee9d08a3791a89a32a22844f04ad025c31",
    git_commit_timestamp: "2023-08-14T22:40:27.000000000Z",
    git_branch: "main",
    rustc_semver: "1.70.0",
    rustc_channel: "stable",
    rustc_host_triple: "x86_64-unknown-illumos",
    rustc_commit_sha: "90c541806f23a127002de5b4038be731ba1458ca",
    cargo_triple: "x86_64-unknown-illumos",
    debug: false,
    opt_level: 3,
}
Crucible runtime is spawned
Aug 17 01:23:41.183 INFO Listening for a CLI connection on: 0.0.0.0:5050
Upstairs <-> Downstairs Message Version: 4
Aug 17 01:23:41.183 INFO Crucible stats registered with UUID: b242d529-fe6f-4afc-b99d-04a734628f27
Aug 17 01:23:41.183 INFO Crucible b242d529-fe6f-4afc-b99d-04a734628f27 has session id: 17fe4903-c653-41df-8a85-6882d91d3156
Aug 17 01:23:41.183 INFO [1] connecting to 127.0.0.1:8820, looper: 1
Aug 17 01:23:41.183 INFO [0] connecting to 127.0.0.1:8810, looper: 0
Aug 17 01:23:41.183 INFO [2] connecting to 127.0.0.1:8830, looper: 2
Aug 17 01:23:41.183 INFO up_listen starts, task: up_listen
Aug 17 01:23:41.183 INFO Wait for all three downstairs to come online
Aug 17 01:23:41.183 INFO Flush timeout: 0.5
Aug 17 01:23:41.183 INFO [1] b242d529-fe6f-4afc-b99d-04a734628f27 looper connected, looper: 1
Aug 17 01:23:41.183 INFO [2] b242d529-fe6f-4afc-b99d-04a734628f27 looper connected, looper: 2
Aug 17 01:23:41.183 INFO [0] b242d529-fe6f-4afc-b99d-04a734628f27 looper connected, looper: 0
Aug 17 01:23:41.183 INFO [1] Proc runs for 127.0.0.1:8820 in state New
Aug 17 01:23:41.183 INFO [2] Proc runs for 127.0.0.1:8830 in state New
Aug 17 01:23:41.184 INFO [0] Proc runs for 127.0.0.1:8810 in state New
Aug 17 01:23:41.184 INFO [1] b242d529-fe6f-4afc-b99d-04a734628f27 (2b4a3054-8295-48f9-a0a5-004cee454f82) New New New ds_transition to WaitActive
Aug 17 01:23:41.184 INFO [1] Transition from New to WaitActive
Aug 17 01:23:41.184 INFO [2] b242d529-fe6f-4afc-b99d-04a734628f27 (2b4a3054-8295-48f9-a0a5-004cee454f82) New WaitActive New ds_transition to WaitActive
Aug 17 01:23:41.184 INFO [2] Transition from New to WaitActive
Aug 17 01:23:41.184 INFO [0] b242d529-fe6f-4afc-b99d-04a734628f27 (2b4a3054-8295-48f9-a0a5-004cee454f82) New WaitActive WaitActive ds_transition to WaitActive
Aug 17 01:23:41.184 INFO [0] Transition from New to WaitActive
```

Then connect with the cli and tell the upstairs to replace:
```
alan@atrium:crucible$ ./target/release/crutest cli
cli connecting to 0.0.0.0:5050
connected to 0.0.0.0:5050
>> replace --old 127.0.0.1:8830 --new 127.0.0.1:8840
Replace returns: Started
>> 
```

Over on the server, we see it does the replacement:
```
connection from 127.0.0.1:50292

Aug 17 01:24:37.556 WARN 4a85fa95-bd96-4052-b1ff-bc8182903ae7 request to replace downstairs 127.0.0.1:8830 with 127.0.0.1:8840
Aug 17 01:24:37.557 INFO 4a85fa95-bd96-4052-b1ff-bc8182903ae7 found old target: 127.0.0.1:8830 at 2
Aug 17 01:24:37.557 INFO 4a85fa95-bd96-4052-b1ff-bc8182903ae7 replacing old: 127.0.0.1:8830 at 2
Aug 17 01:24:37.557 INFO [2] client skip 0 in process jobs because fault, : downstairs
Aug 17 01:24:37.557 INFO [2] changed 0 jobs to fault skipped, : downstairs
Aug 17 01:24:37.557 INFO [2] b242d529-fe6f-4afc-b99d-04a734628f27 (2b4a3054-8295-48f9-a0a5-004cee454f82) WaitActive WaitActive WaitActive ds_transition to Replacing
Aug 17 01:24:37.557 INFO [2] Transition from WaitActive to Replacing
```

But, .. eh. what should it do here?
Well, it panics if you activate the upstairs:
```
The guest has requested activation with gen:10
Aug 17 01:26:21.855 INFO b242d529-fe6f-4afc-b99d-04a734628f27 active request set
Aug 17 01:26:21.855 INFO Set desired generation to :10
Aug 17 01:26:21.855 INFO [2] received activate with gen 10
Aug 17 01:26:21.855 INFO [2] client got ds_active_rx, promote! session 2b4a3054-8295-48f9-a0a5-004cee454f82
Aug 17 01:26:21.855 INFO [0] received activate with gen 10
Aug 17 01:26:21.855 INFO [0] client got ds_active_rx, promote! session 2b4a3054-8295-48f9-a0a5-004cee454f82
Aug 17 01:26:21.855 INFO [1] received activate with gen 10
Aug 17 01:26:21.855 INFO [1] client got ds_active_rx, promote! session 2b4a3054-8295-48f9-a0a5-004cee454f82
Aug 17 01:26:21.859 INFO [1] downstairs client at 127.0.0.1:8820 has UUID 12345678-0000-0000-0000-000000008820
Aug 17 01:26:21.859 INFO [1] Got region def RegionDefinition { block_size: 4096, extent_size: Block { value: 16384, shift: 12 }, extent_count: 128, uuid: 12345678-0000-0000-0000-000000008820, encrypted: false, database_read_version: 1, database_write_version: 1 }
Aug 17 01:26:21.859 INFO b242d529-fe6f-4afc-b99d-04a734628f27 WaitActive WaitActive Replacing
Aug 17 01:26:21.859 INFO [0] downstairs client at 127.0.0.1:8810 has UUID 12345678-0000-0000-0000-000000008810
Aug 17 01:26:21.859 INFO [0] Got region def RegionDefinition { block_size: 4096, extent_size: Block { value: 16384, shift: 12 }, extent_count: 128, uuid: 12345678-0000-0000-0000-000000008810, encrypted: false, database_read_version: 1, database_write_version: 1 }
Aug 17 01:26:21.859 INFO b242d529-fe6f-4afc-b99d-04a734628f27 WaitActive WaitActive Replacing
Aug 17 01:26:21.860 INFO [2] downstairs client at 127.0.0.1:8830 has UUID 12345678-0000-0000-0000-000000008830
Aug 17 01:26:21.860 INFO [2] Got region def RegionDefinition { block_size: 4096, extent_size: Block { value: 16384, shift: 12 }, extent_count: 128, uuid: 12345678-0000-0000-0000-000000008830, encrypted: false, database_read_version: 1, database_write_version: 1 }
Aug 17 01:26:21.860 WARN [2] exits negotiation, replacing
Aug 17 01:26:21.860 ERRO 127.0.0.1:8830: proc: [2] exits negotiation, replacing, looper: 2
Aug 17 01:26:21.860 INFO [2] b242d529-fe6f-4afc-b99d-04a734628f27 Gone missing, transition from Replacing to Replaced
Aug 17 01:26:21.860 INFO [2] b242d529-fe6f-4afc-b99d-04a734628f27 connection to 127.0.0.1:8830 closed, looper: 2
Aug 17 01:26:21.860 INFO [2] 127.0.0.1:8830 task reports connection:false
Aug 17 01:26:21.860 INFO b242d529-fe6f-4afc-b99d-04a734628f27 WaitActive WaitActive Replaced
Aug 17 01:26:21.860 INFO [2] 127.0.0.1:8830 task reports offline
Aug 17 01:26:21.931 INFO [0] b242d529-fe6f-4afc-b99d-04a734628f27 (2b4a3054-8295-48f9-a0a5-004cee454f82) WaitActive WaitActive Replaced ds_transition to WaitQuorum
Aug 17 01:26:21.931 INFO [0] Transition from WaitActive to WaitQuorum
Aug 17 01:26:21.931 WARN [0] new RM replaced this: None
Aug 17 01:26:21.932 INFO [0] Starts reconcile loop
Aug 17 01:26:21.932 INFO [0] 127.0.0.1:8810 task reports connection:true
Aug 17 01:26:21.932 INFO b242d529-fe6f-4afc-b99d-04a734628f27 WaitQuorum WaitActive Replaced
Aug 17 01:26:21.932 INFO Waiting for 2 more clients to be ready
Aug 17 01:26:21.932 INFO Set check for repair
Aug 17 01:26:21.939 INFO [1] b242d529-fe6f-4afc-b99d-04a734628f27 (2b4a3054-8295-48f9-a0a5-004cee454f82) WaitQuorum WaitActive Replaced ds_transition to WaitQuorum
Aug 17 01:26:21.939 INFO [1] Transition from WaitActive to WaitQuorum
Aug 17 01:26:21.940 WARN [1] new RM replaced this: None
Aug 17 01:26:21.940 INFO [1] Starts reconcile loop
Aug 17 01:26:21.940 INFO [1] 127.0.0.1:8820 task reports connection:true
Aug 17 01:26:21.940 INFO b242d529-fe6f-4afc-b99d-04a734628f27 WaitQuorum WaitQuorum Replaced
Aug 17 01:26:21.940 INFO Waiting for 1 more clients to be ready
Aug 17 01:26:21.940 INFO Set check for repair
Aug 17 01:26:22.861 INFO [2] b242d529-fe6f-4afc-b99d-04a734628f27 looper connected, looper: 2
Aug 17 01:26:22.861 INFO [2] Proc runs for 127.0.0.1:8840 in state Replaced
Aug 17 01:26:22.940 INFO Checking if live repair is needed
Aug 17 01:26:23.005 INFOthread 'tokio-runtime-worker' panicked at '[2] b242d529-fe6f-4afc-b99d-04a734628f27 Initializing Negotiation failed, Replaced -> WaitActive', upstairs/src/lib.rs:6377 [2] b242d529-fe6f-4afc-b99d-04a734628f27 (2b4a3054-8295-48f9-a0a5-004cee454f82) WaitQuorum WaitQuorum Replaced ds_transition to WaitActive:
21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We can't really support replacement before activation, as we don't know yet what our generation number will be
and we don't know what differences exist yet.  

You could make an argument that we need some path to replace a downstairs, but if we do that before activation,
we have to be sure that only one downstairs has been replaced, and we don't try to replace 2, or 3 downstairs
before activation, as that can lead to data loss.

**Comment by leftwo** [comment]
This same sort of "how do we replace a downstairs if there is no active upstairs" exists for disks not attached,
or attached to a stopped instance.  The pantry needs to get involved in those cases.

**Comment by mkeeter** [comment]
There's still an issue here after the single-task refactoring (#1058), but the behavior is different: if you replace before activation, then upon activation, the Upstairs panics with
```
thread 'tokio-runtime-worker' panicked at upstairs/src/client.rs:748:18:
invalid state for set_active_request: Replaced
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We could change that check to allow for activation from the `Replaced` state, or prevent replacement (rejecting `BlockOp::ReplaceDownstairs`) if the Upstairs is not active.  Both are easy changes, but I'm not what the correct behavior should be.

**Comment by leftwo** [comment]
I think the solution here needs to come from a larger context of information, and probably more
saveguards needs to be built into the overall downstairs replacement framework.

We can, and need to support replacement of a downstairs when there is no upstairs, or even right before the
upstairs goes active, but we can't replace more than one downstairs at a time,  We need the three downstairs
to be synced up.  I fear that someone could replace one, two, then the third downstairs before we actually
make them consistent and then we have essentially lost the data.

**Comment by leftwo** [comment]
This situation can also happen if a replace request comes in during a reconciliation.
In that case the replacement causes the reconciliation to fail, but then leaves things
broken and we can no longer make forward progress. https://github.com/oxidecomputer/crucible/pull/1269#issuecomment-2076023390

I think there are a few ways we can handle this, but a possible solution is to refuse
any replacement of a downstairs when we are not active.  

So either we have to have started the guest/volume/pantry/whatever with a VCR 
that has one new and two old downstairs and let reconciliation handle the 
replacement;  Or, we are active and can accept a downstairs replacement and go 
through LiveRepair with it.

We will have to rely on Nexus not letting more than one downstairs be replaced at
a time, or having the knowledge to know if we are in a two failed downstairs
state and must allow it.

If we prevent replacement before activation, then we also must have the
ability to "fail" and let the replacement (and subsiquent reconciliation) try again.
This could be either
1. The upstairs will detect when it can't reconcile with the downstairs it has and fail back to a place where a new VCR can be accepted and try again.
2. The pantry or instance that can't reconcile with the downstairs it has can be stopped/aborted through some other mechanism and the replacement can come in with a new VCR and we start over the reconciliation.

I think the second idea makes better sense as Nexus has a better view into the overall state
of things and could have more information than the upstairs.

**Comment by leftwo** [comment]
Fixed with 1381
